require:
 - rubocop-rspec
 - rubocop-performance
 - rubocop-thread_safety
 - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
  - 'db/migrate/*'

Layout/FirstHashElementIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
