require:
 - rubocop-rspec
 - rubocop-performance
 - rubocop-thread_safety
 - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
  - 'db/migrate/*'

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
