x-app: &app
  stdin_open: true
  tty: true
  pull_policy: never
  image: subscription_rebilling
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    REDIS_URL: redis://redis:6379/
    PAYMENT_GATEWAY_URL: http://mocked_payment_gateway:3333
  volumes:
    - .:/app
  depends_on:
    redis:
      condition: service_healthy

services:
  app:
    <<: *app
    depends_on:
      sidekiq:
        condition: service_started
      sidekiq_web:
        condition: service_started
      mocked_payment_gateway:
        condition: service_started

  sidekiq:
    <<: *app
    command: bundle exec sidekiq -r ./config/application.rb

  sidekiq_web:
    <<: *app
    command: bundle exec rackup -o 0.0.0.0 runner.ru
    ports:
      - '9292:9292'
    volumes:
      - ./config/sidekiq_web.ru:/app/runner.ru

  mocked_payment_gateway:
    <<: *app
    command: bundle exec ruby runner.rb
    ports:
      - '3333:3333'
    volumes:
      - ./config/mocked_payment_gateway.rb:/app/runner.rb

  redis:
    image: redis:7.4.1
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  redis:
